logging:
  level:
    org.springframework.security.web.csrf: DEBUG
    com.ff.backend.service.impl.DatabaseUserDetailsService: DEBUG

spring:
  application:
    name: backend
  profiles:
    # 默认激活 local profile（Spring Boot 会自动加载并合并 application-local.yml）
    active: local

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    csrf:
      enabled: true